### ISSUE TITLE
Ticker API is not working after upgrade

### ISSUE THREAD

**Issue by aandac** [VebitcoinTeknoloji/tickers-api#1]
API call returns empty results. For XRP

> {"Last":0.0,"High":0.0,"Low":0.0,"Vwap":0.0,"Volume":0.0,"Bid":0.0,"Ask":0.0,"Time":"0001-01-01T00:00:00","Open":0.0}

**Comment by VebitcoinTeknoloji** [comment]
Hi, 
API released we're sorry that issue. Now fixed.
Please check read me documents we supports more tickers than before.

**Comment by VebitcoinTeknoloji** [comment]
Issue fixed
